package com.mh.gui;

import com.mh.exceptions.QuantityExceededException;
import com.mh.exceptions.NotValidPositionException;
import com.mh.exceptions.NotEnoughMoneyException;
import com.mh.biz.Helado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.mh.biz.MaquinaDeHelados;
import com.mh.biz.Venta;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


public class GUI extends javax.swing.JFrame {

    MaquinaDeHelados mdh = new MaquinaDeHelados();

//        Toolkit.getDefaultToolkit().beep();
    public GUI() {
        initComponents();
        try {
            ArrayList<Helado> listaHelados = mdh.getHelados();
            cargarTabla(listaHelados);
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(getClass().getResource("../sonido/camionHelados.wav"));
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            //clip.start();
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMonedas = new javax.swing.JToggleButton();
        botonPosicion9 = new javax.swing.JButton();
        botonPosicion0 = new javax.swing.JButton();
        botonPosicion1 = new javax.swing.JButton();
        botonPosicion2 = new javax.swing.JButton();
        botonPosicionReset = new javax.swing.JButton();
        botonPosicion3 = new javax.swing.JButton();
        botonPosicion4 = new javax.swing.JButton();
        botonPosicion5 = new javax.swing.JButton();
        botonPosicion6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHelados = new javax.swing.JTable();
        inputPosicion = new javax.swing.JTextField();
        botonPedir = new javax.swing.JButton();
        botonSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        visualMonedero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonPosicion7 = new javax.swing.JButton();
        botonDevolverDinero = new javax.swing.JButton();
        botonPosicion8 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBarra = new javax.swing.JMenu();
        submenuVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonMonedas.setForeground(new java.awt.Color(0, 0, 0));
        botonMonedas.setText("Introduce Monedas");
        botonMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMonedasActionPerformed(evt);
            }
        });
        jPanel1.add(botonMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 160, -1));

        botonPosicion9.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion9.setText("9");
        botonPosicion9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion9MouseClicked(evt);
            }
        });
        jPanel1.add(botonPosicion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 40, 40));

        botonPosicion0.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion0.setText("0");
        botonPosicion0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion0MouseClicked(evt);
            }
        });
        botonPosicion0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion0ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion0, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 40, 40));

        botonPosicion1.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion1.setText("1");
        botonPosicion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion1MouseClicked(evt);
            }
        });
        botonPosicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 40, 40));

        botonPosicion2.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion2.setText("2");
        botonPosicion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion2MouseClicked(evt);
            }
        });
        botonPosicion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 40, 40));

        botonPosicionReset.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicionReset.setText("Reset");
        botonPosicionReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicionResetMouseClicked(evt);
            }
        });
        botonPosicionReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicionResetActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicionReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 80, 40));

        botonPosicion3.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion3.setText("3");
        botonPosicion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion3MouseClicked(evt);
            }
        });
        botonPosicion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 40, 40));

        botonPosicion4.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion4.setText("4");
        botonPosicion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion4MouseClicked(evt);
            }
        });
        botonPosicion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 40, 40));

        botonPosicion5.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion5.setText("5");
        botonPosicion5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion5MouseClicked(evt);
            }
        });
        botonPosicion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 40, 40));

        botonPosicion6.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion6.setText("6");
        botonPosicion6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion6MouseClicked(evt);
            }
        });
        jPanel1.add(botonPosicion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 40, 40));

        tablaHelados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Posicion", "Nombre", "Precio", "Tipo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHelados.getTableHeader().setReorderingAllowed(false);
        tablaHelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHeladosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHelados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 580, 259));

        inputPosicion.setEditable(false);
        inputPosicion.setToolTipText("Pedro Sanchez Dimision");
        inputPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPosicionActionPerformed(evt);
            }
        });
        jPanel1.add(inputPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 125, 50));

        botonPedir.setForeground(new java.awt.Color(0, 0, 0));
        botonPedir.setText("Pedir");
        botonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedirActionPerformed(evt);
            }
        });
        jPanel1.add(botonPedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        botonSalida.setBackground(new java.awt.Color(0, 0, 0));
        botonSalida.setForeground(new java.awt.Color(255, 255, 255));
        botonSalida.setText("Salir");
        botonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 89, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduce Posicion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 125, 30));

        visualMonedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        visualMonedero.setForeground(new java.awt.Color(0, 0, 0));
        visualMonedero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visualMonedero.setText("0,00€");
        jPanel1.add(visualMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 60, 40));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Monedero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        botonPosicion7.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion7.setText("7");
        botonPosicion7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion7MouseClicked(evt);
            }
        });
        botonPosicion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion7ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, 40));

        botonDevolverDinero.setForeground(new java.awt.Color(0, 0, 0));
        botonDevolverDinero.setText("Devolver Dinero");
        botonDevolverDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverDineroActionPerformed(evt);
            }
        });
        jPanel1.add(botonDevolverDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        botonPosicion8.setForeground(new java.awt.Color(0, 0, 0));
        botonPosicion8.setText("8");
        botonPosicion8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPosicion8MouseClicked(evt);
            }
        });
        botonPosicion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPosicion8ActionPerformed(evt);
            }
        });
        jPanel1.add(botonPosicion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 40, 40));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mh/imagenes/helado2.jpg"))); // NOI18N
        imagen.setAlignmentY(0.0F);
        imagen.setIconTextGap(0);
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        menuBarra.setText("Menu");

        submenuVenta.setText("Venta");
        submenuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuVentaActionPerformed(evt);
            }
        });
        menuBarra.add(submenuVenta);

        jMenuBar1.add(menuBarra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPosicionActionPerformed
        if (inputPosicion.getText().length() > 2) {
            inputPosicion.setText("");

        }
    }//GEN-LAST:event_inputPosicionActionPerformed

    private void botonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres salir?");
        if (opcion == JOptionPane.YES_OPTION) {
            if (mdh.getMonedero() > 0) {
                JOptionPane.showMessageDialog(this, "Aqui tienes tu cambio: " + String.format("%.2f€", mdh.getMonedero()).replace('.', ','));
            }
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalidaActionPerformed

    private void botonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedirActionPerformed
        String posicion = inputPosicion.getText();
        try {
            Helado conseguido = mdh.pedirHelado(posicion);
            if (conseguido != null) {
                JOptionPane.showMessageDialog(this, "Aquí tiene su " + conseguido.getNombre() + " de tipo " + conseguido.getTipo());
                actualizarMonedero();
                cargarTabla(mdh.getHelados());
            }
        } catch (NotValidPositionException e) {
            JOptionPane.showMessageDialog(this, "Posición introducida inexistente");
        } catch (QuantityExceededException e) {
            JOptionPane.showMessageDialog(this, "No quedan helados en esa posición");
        } catch (NotEnoughMoneyException e) {
            JOptionPane.showMessageDialog(this, "No tiene dinero suficiente para ese helado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Se ha producido un error inesperado. Por favor, contacte con el administrador.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonPedirActionPerformed

    private void botonDevolverDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverDineroActionPerformed
        if (mdh.getMonedero() > 0) {
            JOptionPane.showMessageDialog(this, "Aqui tienes tu cambio: " + String.format("%.2f€", mdh.getMonedero()).replace('.', ','));
            mdh.setMonedero(0.00);
            actualizarMonedero();
        }
    }//GEN-LAST:event_botonDevolverDineroActionPerformed

    private void tablaHeladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHeladosMouseClicked
        int filaSeleccionada = tablaHelados.getSelectedRow();
        String posicion = tablaHelados.getValueAt(filaSeleccionada, 0).toString();
        inputPosicion.setText(posicion);
    }//GEN-LAST:event_tablaHeladosMouseClicked

    private void submenuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuVentaActionPerformed
        try {
            ArrayList<Venta> listaVentas = mdh.getVentas();
            InformeVentas informe = new InformeVentas(listaVentas, this, true);
            informe.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submenuVentaActionPerformed

    private void botonMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMonedasActionPerformed
        IntroducirMonedas monedas = new IntroducirMonedas(this, true);  // true para  modal
        monedas.setVisible(true);
    }//GEN-LAST:event_botonMonedasActionPerformed

    private void botonPosicion0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion0MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 0);
        }
    }//GEN-LAST:event_botonPosicion0MouseClicked

    private void botonPosicion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion1MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 1);
        }
    }//GEN-LAST:event_botonPosicion1MouseClicked

    private void botonPosicion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion2MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 2);
        }
    }//GEN-LAST:event_botonPosicion2MouseClicked

    private void botonPosicion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion2ActionPerformed

    private void botonPosicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion1ActionPerformed

    private void botonPosicionResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicionResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicionResetActionPerformed

    private void botonPosicion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion3MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 3);
        }
    }//GEN-LAST:event_botonPosicion3MouseClicked

    private void botonPosicion4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion4MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 4);
        }
    }//GEN-LAST:event_botonPosicion4MouseClicked

    private void botonPosicion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion4ActionPerformed

    private void botonPosicion5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion5MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 5);
        }
    }//GEN-LAST:event_botonPosicion5MouseClicked

    private void botonPosicion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion5ActionPerformed

    private void botonPosicion6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion6MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 6);
        }
    }//GEN-LAST:event_botonPosicion6MouseClicked

    private void botonPosicion7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion7MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 7);
        }
    }//GEN-LAST:event_botonPosicion7MouseClicked

    private void botonPosicion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion7ActionPerformed

    private void botonPosicion8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion8MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 8);
        }
    }//GEN-LAST:event_botonPosicion8MouseClicked

    private void botonPosicion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion8ActionPerformed

    private void botonPosicion9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicion9MouseClicked
        if (inputPosicion.getText().length() < 2) {
            inputPosicion.setText(inputPosicion.getText() + 9);
        }
    }//GEN-LAST:event_botonPosicion9MouseClicked

    private void botonPosicion0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion0ActionPerformed

    private void botonPosicion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPosicion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPosicion3ActionPerformed

    private void botonPosicionResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPosicionResetMouseClicked
        inputPosicion.setText("");
    }//GEN-LAST:event_botonPosicionResetMouseClicked

    public void cargarTabla(ArrayList<Helado> lista) {
        DefaultTableModel model = (DefaultTableModel) tablaHelados.getModel(); //Cargas la tabla anterior
        model.setRowCount(0); // Borra filas anteriores

        for (Helado h : lista) {
            Object[] fila = {
                h.getPosicion(),
                h.getNombre(),
                String.format("%.2f€", h.getPrecio()).replace('.', ','),
                h.getTipo(),
                h.getCantidad()
            };
            model.addRow(fila); // Añade cada fila
        }
    }

    public void actualizarMonedero() {
        visualMonedero.setText(String.format("%.2f€", mdh.getMonedero()).replace('.', ','));
    }
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDevolverDinero;
    private javax.swing.JToggleButton botonMonedas;
    private javax.swing.JButton botonPedir;
    private javax.swing.JButton botonPosicion0;
    private javax.swing.JButton botonPosicion1;
    private javax.swing.JButton botonPosicion2;
    private javax.swing.JButton botonPosicion3;
    private javax.swing.JButton botonPosicion4;
    private javax.swing.JButton botonPosicion5;
    private javax.swing.JButton botonPosicion6;
    private javax.swing.JButton botonPosicion7;
    private javax.swing.JButton botonPosicion8;
    private javax.swing.JButton botonPosicion9;
    private javax.swing.JButton botonPosicionReset;
    private javax.swing.JButton botonSalida;
    private javax.swing.JLabel imagen;
    private javax.swing.JTextField inputPosicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuBarra;
    private javax.swing.JMenuItem submenuVenta;
    private javax.swing.JTable tablaHelados;
    private javax.swing.JLabel visualMonedero;
    // End of variables declaration//GEN-END:variables

}
