/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mh.gui;


import com.mh.biz.MaquinaDeHelados;
import javax.swing.JOptionPane;

public class IntroducirMonedas extends javax.swing.JDialog {  // Cambiado de JFrame a JDialog
    private final MaquinaDeHelados mdh;
    private final GUI parent;  // Referencia a la ventana padre

    public IntroducirMonedas(GUI parent, boolean modal) {
        super(parent, modal);  // Hacemos la ventana modal
        this.parent = parent;
        this.mdh = parent.mdh;  // Obtenemos la referencia a la máquina de helados
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputMonedas005 = new javax.swing.JButton();
        inputMonedas200 = new javax.swing.JButton();
        inputMonedas010 = new javax.swing.JButton();
        inputMonedas020 = new javax.swing.JButton();
        inputMonedas050 = new javax.swing.JButton();
        inputMonedas100 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inputMonedas005.setText("0,05");
        inputMonedas005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas005ActionPerformed(evt);
            }
        });

        inputMonedas200.setText("2");
        inputMonedas200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas200ActionPerformed(evt);
            }
        });

        inputMonedas010.setText("0,10");
        inputMonedas010.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas010ActionPerformed(evt);
            }
        });

        inputMonedas020.setText("0,20");
        inputMonedas020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas020ActionPerformed(evt);
            }
        });

        inputMonedas050.setText("0,5");
        inputMonedas050.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas050ActionPerformed(evt);
            }
        });

        inputMonedas100.setText("1");
        inputMonedas100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMonedas100ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Introduce Monedas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputMonedas100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputMonedas200, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(inputMonedas005, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputMonedas010, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(inputMonedas020, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputMonedas050, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMonedas010, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMonedas005, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMonedas020, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMonedas050, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputMonedas200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMonedas100, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputMonedas005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas005ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 0.05);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas005ActionPerformed

    private void inputMonedas200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas200ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 2);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas200ActionPerformed

    private void inputMonedas010ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas010ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 0.1);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas010ActionPerformed

    private void inputMonedas020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas020ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 0.2);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas020ActionPerformed

    private void inputMonedas050ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas050ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 0.5);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas050ActionPerformed

    private void inputMonedas100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMonedas100ActionPerformed
        mdh.setMonedero(mdh.getMonedero() + 1);
        parent.actualizarMonedero();
    }//GEN-LAST:event_inputMonedas100ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputMonedas005;
    private javax.swing.JButton inputMonedas010;
    private javax.swing.JButton inputMonedas020;
    private javax.swing.JButton inputMonedas050;
    private javax.swing.JButton inputMonedas100;
    private javax.swing.JButton inputMonedas200;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
